# Generated by Django 2.2 on 2019-04-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
