# Generated by Django 2.2 on 2019-04-02 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20190402_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='points',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='task',
        ),
        migrations.AddField(
            model_name='exam',
            name='name',
            field=models.CharField(default='Exam', max_length=32),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(max_length=512)),
                ('points', models.PositiveSmallIntegerField(default=0)),
                ('exam', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='API.Exam')),
            ],
        ),
    ]
