# Generated by Django 2.2 on 2019-04-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20190402_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='grade',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
