# Generated by Django 2.2 on 2019-04-02 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20190402_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Exam'),
        ),
    ]
